chore: bump version and enhance WebScraper error handling
- Update version from 0.0.2 to 0.0.4 in multiple configuration files
- Add a message field to the WebScraperStatus type
- Modify the CRD to include the new message field
- Adjust Docker build command to include a new image tag
- Update sample CronJob configuration to include retry logic
- Improve error logging for job status updates in the WebScraper reconciler

Signed-off-by: Sean Zheng <blackhorseya@gmail.com>

diff --git a/config/samples/batch_v1_webscraper.yaml b/config/samples/batch_v1_webscraper.yaml
--- a/config/samples/batch_v1_webscraper.yaml
+++ b/config/samples/batch_v1_webscraper.yaml
@@ -6,17 +6,17 @@ metadata:
     app.kubernetes.io/managed-by: kustomize
   name: webscraper-sample
 spec:
-  schedule: "*/1 * * * *" # 每分钟触发一次 CronJob
+  schedule: "*/1 * * * *" # 每分钟触发一次
   image: "busybox"
   command:
     - sh
     - -c
     - |
-      while true; do
-        if [ $((RANDOM % 2)) -eq 0 ]; then
-          echo "Success";
-        else
-          echo "Failure";
-        fi
-        sleep 5;
-      done
+      if [ $((RANDOM % 2)) -eq 0 ]; then
+        echo "Success";
+        exit 0;
+      else
+        echo "Failure";
+        exit 1;
+      fi
+  retries: 3
